<?php View::content() ?>

<div class="form-group">
</div>
<div class="card">
    <img class="card-img-top" src="holder.js/100x180/" alt="">
    <div class="card-body">
        <h4 class="card-title">BIENVENIDO POR FAVOR IDENTIFIQUESE</h4>
        <form action="logguear" method="post">
            <div class="form-group">
                <label for="">Nombre de usuario</label>
                <input type="text" name="nombre" id="" class="form-control" placeholder="" aria-describedby="helpId">
            </div>

            <div class="form-group">
                <label for="">Password</label>
                <input type="password" name="pass" id="" class="form-control" placeholder="" aria-describedby="helpId">
            </div>

        <input type="submit" value="Entrar">
        </form>
</div>
</div>