<div id="scaffold">
<?php View::content() ?>
<h1><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
<form action="",  method="post">
<?php foreach ($registro  as $r => $field): ?>
<div class="form-group">
	<label for=""> <?=$r ?> </label>
	<input type="text" name="<?=$r ?>" id="" class="form-control" value="<?= $field?>">

</div>
<?php endforeach ?>
<input type="submit" value="Actualizar" class="btn btn-primary btn-block">

</form>
<div class="col-12">
	<br>
	<a href="../" class="btn btn-secondary btn-block">Listado</a>
</div>
<?php //View::partial('editors/tinymce') // ya veremos si incluimos algun wysiwyg?>
</div>