<div id="scaffold">
<?php View::content()?>
<?php if ($data) : ?>
	<h1><?= ucwords("$model"),": <span>$action_name</span>" ?></h1>
	<ul>
	<table class="table table-striped table-inverse table-bordered">
    <thead class="thead-inverse"><tr>
    <?php foreach ($data as $r => $field) : ?>
        <th><?= $r?></th>
	<?php endforeach?>
	<th>Acciones</th>
    </tr></thead>
	<tbody>
        <tr>
		<?php foreach ($data as $r => $field) : ?>
            <td><?= $field?></td>
		<?php endforeach?>
			<td><?= Html::linkAction("ver/$data->id", 'Ver', 'class="btn btn-primary"')?> |
			<?= Html::linkAction("editar/$data->id", 'Editar', 'class="btn btn-secondary"')?> |
			<?= Html::linkAction("borrar/$data->id", 'Borrar', 'class="btn btn-danger"', 'onclick="return confirm(\'¿Está seguro?\')"') ?>
			</td>

	</tbody>
</table>
	<?php foreach ($data->fields as $field) : ?>
		
	<?php endforeach ?>
	</ul>

	
<?php else : ?>
	<?php http_response_code(404)?>
	<h1>No existe</h1>
	<div class="actions">
		<a href="../">Listado</a>
		<a href="../crear/">Crear registro</a>
	</div>
<?php endif ?>
</div>
